### PR TITLE
Get the current temperature from Tasmota Device

### PR DESCRIPTION
**Pull request by macjl**
This is the PR for #5.

### CODE REVIEW

**Review by jhthorsen — CHANGES_REQUESTED** [review]

**Comment by jhthorsen** [comment]
What is the status here @macjl?

**Comment by macjl** [comment]
Sorry. I was very busy last weeks because of a new job. This is still on my todo. I’ll try to have a look before next week-end.

**Comment by jhthorsen** [comment]
Ah! Congratulations :)
Just wanted to be sure you didn’t wait for me 👍

**Comment by macjl** [comment]
I changed the logic as you said.

But I think there is something is still missing : when the temperature is retrieved from Tasmota, we have to call [updateValue](https://developers.homebridge.io/#/api/characteristics#characteristicupdatevalue), to notify HomeKit of the new temperature. I will add that in next Commit.

**Comment by macjl** [comment]
I think all the issue I've found are now resolved. Do you think there are something else I have to do for this PR ?

**Review by jhthorsen — APPROVED** [review]
There's some minor things I want to change, but I can do that locally.

**Comment by rajattrehan21** [comment]
Nevermind. Got everything working with the current temperature. This plugin is awesome. Thanks a ton.

**Pull request merged**
